version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    extra_hosts:
      # needs '127.0.0.1 host.docker.internal' at /etc/hosts or windows' host file
      - "host.docker.internal:172.17.0.1"